### ISSUE TITLE
loosing connection

### ISSUE THREAD

**Issue by icygame** [FlyingDiver/Indigo-UDP-Listener#1]
On Mojave 10.14 / Indigo 7.02, the UDP listener is ceasing to operate after an indefinite period ( i'm (but provides no error message I have identified thus far). 

The problem is fixed with a restart of the plugin (but eventually repeats). Connection status (and the timing of lost connectivity) is not immediately  apparent other than though the absence of  UDP messages detected after a known event - however I suspect a factor may be the host Macbook Air returning from (an unwanted period of) sleep mode.

Update: I've tracked down an error message sequence in the logs which confirms this is related to a sleep issue.  I have recurring issues preventing the Mac in question sleeping: obviously that would be a preferable solution. I have not filtered notifications form other plugins (these do return to normal operation).

`16 Oct 2018 at 4:41:53 am
   Received sleep notification from system
   Cynical Network                 going to sleep
   Cynical Network                 FRONT GATE global cache flex device stopping
   UDP Listener Debug              Removing Trigger gate closing (starts) (1558505606)
   UDP Listener Debug              Removing Trigger gate closing cycle (ends) (95468336)
   UDP Listener Debug              Removing Trigger gate open request (button off) (630556779)
   UDP Listener Debug              Removing Trigger gate open request (button on) (851253716)
   UDP Listener Debug              UDP gate event listener: Unknown Device ID: 1476864657
   Power Source Error              Unknown battery: BR850ELCD

16 Oct 2018 at 6:42:03 am
   Hue Lights Error                Failed to connect to the Hue hub at 192.168.0.161. - Check that the hub is connected, turned on and the network settings are correct.
   Z-Wave Error                    serial port communication error: read failed: [Errno 6] Device not configured
   Z-Wave Error                    Z-Wave 3.95 static controller might be disconnected
   Z-Wave Error                    silently retrying serial connection every 5.0 seconds
   Received awake notification from system
   Cynical Network                 waking up
   UDP Listener Debug              UDP gate event listener: Device Current Version = 0
   UDP Listener Debug              UDP gate event listener: Device Version is up to date
   UDP Listener Debug              UDP gate event listener: Starting device (udpListener)
   UDP Listener Error              exception in deviceStartComm(UDP gate event listener): [Errno 49] Can't assign requested address`

While the 'automatic' attempt to reconnect returns this error, a reload of the plugin does not.

**Comment by FlyingDiver** [comment]
I'm not sure this is really solvable. I'm not sure if Indigo itself is designed to handle going to sleep properly.  Need to look into that.

**Comment by FlyingDiver** [comment]
So this is interesting.  This line shouldn't be happening:

    UDP Listener Debug UDP gate event listener: Unknown Device ID: 1476864657

That's saying that the plugin had an error when trying to shut down the UDP listener device when the system was about to go to sleep.

Then this error:

    UDP Listener Error exception in deviceStartComm(UDP gate event listener): [Errno 49] Can't assign requested address

is because the port wasn't previously released so it can't bind to it.  

If I can fix the first error, the send should go away and it should work properly after a sleep interval.

**Comment by FlyingDiver** [comment]
Please install this version:  https://github.com/FlyingDiver/Indigo-UDP-Listener/releases/tag/0.0.6

Then do a plugin restart with debug logging and send me the log output.

**Comment by icygame** [comment]
thanks! here is the log following a restart:

````
17 Oct 2018 at 9:25:37 am
   Reloading plugin "UDP Listener 0.0.6"
   Stopping plugin "UDP Listener 0.0.6" (pid 90877)
   UDP Listener Debug              Removing Trigger gate closing (starts) (1558505606)
   UDP Listener Debug              Removing Trigger gate closing cycle (ends) (95468336)
   UDP Listener Debug              Removing Trigger gate open request (button off) (630556779)
   UDP Listener Debug              Removing Trigger gate open request (button on) (851253716)
   UDP Listener Debug              UDP gate event listener: Stopping udpListener device (1476864657)
   UDP Listener                    Shutting down UDP Listener
   Stopped plugin "UDP Listener 0.0.6"
   Starting plugin "UDP Listener 0.0.6" (pid 90960)
   UDP Listener Debug              logLevel = 5
   Started plugin "UDP Listener 0.0.6"
   UDP Listener                    Starting UDP Listener
   UDP Listener Threaddebug        UDP gate event listener: Device Current Version = 0
   UDP Listener Threaddebug        UDP gate event listener: Device Version is up to date
   UDP Listener Debug              UDP gate event listener: Starting udpListener device (1476864657)
   UDP Listener Debug              Adding Trigger gate closing (starts) (1558505606) - messageReceived
   UDP Listener Debug              Adding Trigger gate closing cycle (ends) (95468336) - messageReceived
   UDP Listener Debug              Adding Trigger gate open request (button off) (630556779) - messageReceived
   UDP Listener Debug              Adding Trigger gate open request (button on) (851253716) - messageReceived
````
I have also manually forced a sleep and re-awake cycle  - everything appears to operate normally after the cycle, with no errors reported.

Thanks for your assistance on this, especially since its obviously an edge-case (though hopefully this might help others after a shutdown!).

**Comment by FlyingDiver** [comment]
There was something going on with the device that the plugin was unable to stop. Without that error, I don't think there's anything else to fix.
